"""add course

Revision ID: 018c127c9131
Revises: 537fbc202b20
Create Date: 2021-07-14 14:45:27.537472

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '018c127c9131'
down_revision = '537fbc202b20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta', sa.JSON(), server_default='{}', nullable=True),
    sa.Column('course_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('course_name', sa.String(length=100), nullable=False),
    sa.Column('course_code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('instructor', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('course_id'),
    sa.UniqueConstraint('course_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course')
    # ### end Alembic commands ###
