"""add enrolment model

Revision ID: 4c41d06490c8
Revises: 018c127c9131
Create Date: 2021-08-19 13:52:16.180647

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4c41d06490c8'
down_revision = '018c127c9131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrolment',
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta', sa.JSON(), server_default='{}', nullable=True),
    sa.Column('enrolment_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('student_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('course_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.student_id'], ),
    sa.PrimaryKeyConstraint('enrolment_id'),
    sa.UniqueConstraint('student_id', 'course_id', name='unq_student_course')
    )
    op.create_index(op.f('ix_enrolment_course_id'), 'enrolment', ['course_id'], unique=False)
    op.create_index(op.f('ix_enrolment_student_id'), 'enrolment', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enrolment_student_id'), table_name='enrolment')
    op.drop_index(op.f('ix_enrolment_course_id'), table_name='enrolment')
    op.drop_table('enrolment')
    # ### end Alembic commands ###
